export const faixasEGraus: { faixa: string; grau: number| null }[] = [
  { faixa: "BRANCA", grau: null },
  { faixa: "BRANCA", grau: 1 },
  { faixa: "BRANCA", grau: 2 },
  { faixa: "BRANCA", grau: 3 },
  { faixa: "BRANCA", grau: 4 },

  { faixa: "CINZA/BRANCA", grau: null },
  { faixa: "CINZA/BRANCA", grau: 1 },
  { faixa: "CINZA/BRANCA", grau: 2 },
  { faixa: "CINZA/BRANCA", grau: 3 },
  { faixa: "CINZA/BRANCA", grau: 4 },

  { faixa: "CINZA", grau: null },
  { faixa: "CINZA", grau: 1 },
  { faixa: "CINZA", grau: 2 },
  { faixa: "CINZA", grau: 3 },
  { faixa: "CINZA", grau: 4 },

  { faixa: "CINZA/PRETA", grau: null },
  { faixa: "CINZA/PRETA", grau: 1 },
  { faixa: "CINZA/PRETA", grau: 2 },
  { faixa: "CINZA/PRETA", grau: 3 },
  { faixa: "CINZA/PRETA", grau: 4 },

  { faixa: "AMARELA/BRANCA", grau: null},
  { faixa: "AMARELA/BRANCA", grau: 1 },
  { faixa: "AMARELA/BRANCA", grau: 2 },
  { faixa: "AMARELA/BRANCA", grau: 3 },
  { faixa: "AMARELA/BRANCA", grau: 4 },

  { faixa: "AMARELA", grau: null },
  { faixa: "AMARELA", grau: 1 },
  { faixa: "AMARELA", grau: 2 },
  { faixa: "AMARELA", grau: 3 },
  { faixa: "AMARELA", grau: 4 },

  { faixa: "AMARELA/PRETA", grau: null },
  { faixa: "AMARELA/PRETA", grau: 1 },
  { faixa: "AMARELA/PRETA", grau: 2 },
  { faixa: "AMARELA/PRETA", grau: 3 },
  { faixa: "AMARELA/PRETA", grau: 4 },

  { faixa: "LARANJA/BRANCA", grau: null },
  { faixa: "LARANJA/BRANCA", grau: 1 },
  { faixa: "LARANJA/BRANCA", grau: 2 },
  { faixa: "LARANJA/BRANCA", grau: 3 },
  { faixa: "LARANJA/BRANCA", grau: 4 },

  { faixa: "LARANJA", grau: null },
  { faixa: "LARANJA", grau: 1 },
  { faixa: "LARANJA", grau: 2 },
  { faixa: "LARANJA", grau: 3 },
  { faixa: "LARANJA", grau: 4 },

  { faixa: "LARANJA/PRETA", grau: null },
  { faixa: "LARANJA/PRETA", grau: 1 },
  { faixa: "LARANJA/PRETA", grau: 2 },
  { faixa: "LARANJA/PRETA", grau: 3 },
  { faixa: "LARANJA/PRETA", grau: 4 },

  { faixa: "VERDE/BRANCA", grau: null },
  { faixa: "VERDE/BRANCA", grau: 1 },
  { faixa: "VERDE/BRANCA", grau: 2 },
  { faixa: "VERDE/BRANCA", grau: 3 },
  { faixa: "VERDE/BRANCA", grau: 4 },

  { faixa: "VERDE", grau: null },
  { faixa: "VERDE", grau: 1 },
  { faixa: "VERDE", grau: 2 },
  { faixa: "VERDE", grau: 3 },
  { faixa: "VERDE", grau: 4 },

  { faixa: "VERDE/PRETA", grau: null },
  { faixa: "VERDE/PRETA", grau: 1 },
  { faixa: "VERDE/PRETA", grau: 2 },
  { faixa: "VERDE/PRETA", grau: 3 },
  { faixa: "VERDE/PRETA", grau: 4 },

  { faixa: "AZUL", grau: null },
  { faixa: "AZUL", grau: 1 },
  { faixa: "AZUL", grau: 1 },
  { faixa: "AZUL", grau: 2 },
  { faixa: "AZUL", grau: 3 },
  { faixa: "AZUL", grau: 4 },

  { faixa: "ROXA", grau: null },
  { faixa: "ROXA", grau: 1 },
  { faixa: "ROXA", grau: 2 },
  { faixa: "ROXA", grau: 3 },
  { faixa: "ROXA", grau: 4 },

  { faixa: "MARROM", grau: null },
  { faixa: "MARROM", grau: 1 },
  { faixa: "MARROM", grau: 2 },
  { faixa: "MARROM", grau: 3 },
  { faixa: "MARROM", grau: 4 },

  { faixa: "PRETA", grau: null },
  { faixa: "PRETA", grau: 1 },
  { faixa: "PRETA", grau: 2 },
  { faixa: "PRETA", grau: 3 },
  { faixa: "PRETA", grau: 4 },
  { faixa: "PRETA", grau: 5 },
  { faixa: "PRETA", grau: 6 },
  { faixa: "PRETA", grau: 7 },
  { faixa: "PRETA", grau: 8 },
  { faixa: "PRETA", grau: 9 },
  { faixa: "PRETA", grau: 10 },

  { faixa: "VERMELHA", grau: null },
  { faixa: "VERMELHA", grau: 1 },
  { faixa: "VERMELHA", grau: 2 },
  { faixa: "VERMELHA", grau: 3 },
  { faixa: "VERMELHA", grau: 4 },
  { faixa: "VERMELHA", grau: 5 },
  { faixa: "VERMELHA", grau: 6 },
  { faixa: "VERMELHA", grau: 7 },
  { faixa: "VERMELHA", grau: 8 },
  { faixa: "VERMELHA", grau: 9 },
];